# -*- coding: utf-8 -*-
"""Q.2 ASSIGNMENT BY RISHIK CHAUDHARY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lP66HqrSc_t00TzkO-UQ8ELnC0V7oHgB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path=("/content/drive/MyDrive/DATASET/gpa_iq.csv")
df=pd.read_csv(path)
df.head()

df.isnull().sum()

df.drop(columns=["gender","obs","concept"])

plt.scatter(df['gpa'],df['iq'])

#Q.2 of assignment
#using k means to find the clustering in the dataset given above
from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11):
  km=KMeans(n_clusters=i)
  km.fit_predict(df)
  wcss.append(km.inertia_)

wcss

plt.plot(range(1,11),wcss)

x=