# -*- coding: utf-8 -*-
"""Q.3 OF ASSIGNMENT BY RISHIK CHAUDHARY

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xAHEGWdG_eO-0NOV5P3BF0pHt4OAB1xH
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

path=("/content/drive/MyDrive/DATASET/iris.data")
df=pd.read_csv(path)

df.head()

df.isnull().sum()

df.info()

#checking clusters of the saple length using the scatter plot graph
plt.scatter(df["5.1"],df["3.5"])

from sklearn.cluster import KMeans
wcss=[]
data=df[['5.1','3.5']]
for i in range(1,21):
  km=KMeans(n_clusters=i)
  km.fit_predict(data)
  wcss.append(km.inertia_)

wcss

plt.plot(range(1,21),wcss)

x=data.iloc[:,:].values
km=KMeans(n_clusters=5)
y_means=km.fit_predict(x)

y_means

x[y_means==3,1]

plt.scatter(x[y_means==0,0],x[y_means==0,1],color='blue')

#printing cluster in our data set using the scatter plot graph
plt.scatter(x[y_means==1,0],x[y_means==1,1],color='red')
plt.scatter(x[y_means==2,0],x[y_means==2,1],color='green')
plt.scatter(x[y_means==3,0],x[y_means==3,1],color='blue')